### ISSUE TITLE
installation docs?

### ISSUE THREAD

**Issue by fommil** [Fanael/persistent-scratch#1]
this sounds nice! I'd like to use it, but I couldn't work out how to get it working.

I put this in my .emacs

``` elisp
(require 'persistent-scratch)
(persistent-scratch--turn-autosave-on)
(persistent-scratch-restore-from-file)
```

but all I get is an error on startup (and I'm pretty sure I shouldn't be using your internal double-dash function) and then I tried setting setting

```
(setq persistent-scratch-backup-directory (concat user-emacs-directory "scratch"))
```

but I'm not getting persistent settings.

Do you have an example snippet of how to enable?

**Comment by Fanael** [comment]
First things first: the recommended (and the only supported, really) way to install the package is via `package.el`. Thus, to install this package, use either [MELPA](http://melpa.org/) or [MELPA Stable](http://stable.melpa.org/), or visit `persistent-scratch.el` and call `M-x package-install-from-buffer`.

>  I'm pretty sure I shouldn't be using your internal double-dash function

Yeah. What you want is to enable `persistent-scratch-autosave-mode`, as mentioned in the commentary.

> ``` emacs-lisp
> (persistent-scratch-restore-from-file)
> ```

This won't work. `persistent-scratch-restore-from-file` requires an argument. I guess that you actually want `(persistent-scratch-restore)`, which restores scratch buffers from `persistent-scratch-save-file`.

This, still, could error if `persistent-scratch-save-file` is not available. As mentioned in the commentary, again, wrap the call in `ignore-errors`, or possibly `with-demoted-errors`:

``` emacs-lisp
(with-demoted-errors "Cannot restore scratch buffers: %S"
  (persistent-scratch-restore))
```

**Comment by fommil** [comment]
Thanks! BTW, I'm using MELPA. It would be nice if everything "just worked" when `(require persistent-scratch)` is called.

I got it working with

```
(ignore-errors (persistent-scratch-restore))
```

But like I said above, it would be good to not have to do this. At the very least, a cleaner version of (persistent-scratch-restore) that doesn't error would be good. I like to keep my .emacs tidy :smile:

**Comment by Fanael** [comment]
> It would be nice if everything "just worked" when `(require persistent-scratch)` is called.

Won't happen. Not only because you forgot to quote the package name, but also because minor modes enabling themselves when loaded is bad style and @purcell wouldn't allow the package in MELPA if it did that.

> But like I said above, it would be good to not have to do this. At the very least, a cleaner version of (persistent-scratch-restore) that doesn't error would be good.

I can think about that.

**Comment by Fanael** [comment]
By the way, explicitly `require`ing the package is not necessary. The autoload cookies are there for a reason.

**Comment by Fanael** [comment]
In version 0.2 all that's needed to enable autosave _and_ restore the last saved state is to call `persistent-scratch-setup-default`. I think that that's close to what you want.

**Comment by fommil** [comment]
cool! I'm also happy with your default file for this, so that works very well :smile: Looking forward to it hitting MELPA
