### ISSUE TITLE
Update emacs version dependency

### ISSUE THREAD

**Issue by jezcope** [Fanael/persistent-scratch#16]
Is the dependency on Emacs 24 correct? Because it's specified in the package metadata I can't install this from MELPA on Emacs 26.1. I don't know if it's specified because it doesn't work at all in >24, or if it's just an oversight.

**Comment by jezcope** [comment]
PS. I haven't got round to installing it manually and testing it yet but I can do if it hasn't been done.

**Comment by Fanael** [comment]
I just loaded it successfully in a month-old git master snapshot, which is newer than 26.1. What is the exact error message?

**Comment by jezcope** [comment]
Never mind, for some reason it wasn't appearing in my package-list but now it is.
