### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by xmaillard** [Fanael/persistent-scratch#2]
Hello,

Would you mind be more precise about the license covered by your mode ?

I am looking for a mode named like yours but I do not remember it to be that "long" and mainly, covered by the GPL license.

Thank you

**Comment by Fanael** [comment]
> Would you mind be more precise about the license covered by your mode ?

[The source file is pretty precise about that](https://github.com/Fanael/persistent-scratch/blob/master/persistent-scratch.el#L10): it's 2-clause BSD license.

> I am looking for a mode named like yours but I do not remember it to be that "long" and mainly, covered by the GPL license.

Had I known a mode like this already exists, I wouldn't've reinvented the wheel. At any rate, this code is written from scratch.

**Comment by xmaillard** [comment]
Fanael Linithien notifications@github.com writes:

> > Would you mind be more precise about the license covered by your mode ?
> 
> [The source file is pretty precise about that](https://github.com/Fanael/persistent-scratch/blob/master/persistent-scratch.el#L10): it's 2-clause BSD license.

Ooops :/ Misread something ... :)

> > I am looking for a mode named like yours but I do not remember it to be that "long" and mainly, covered by the GPL license.
> 
> Had I known a mode like this already exists, I wouldn't've reinvented the wheel. At any rate, this code is written from scratch.

No offense here :-)

I have found several other modes with the same goals:
- scratch-persist: https://github.com/nflath/scratch-persist/blob/master/scratch-persist.el
- persistent-scratch: https://github.com/krobertson/emacs.d/blob/master/configs/persistent-scratch.el
- scratch-backup: https://github.com/davepen/emacs.d/blob/master/scratch-backup.el
- persistent-scratch: https://github.com/adamrt/emacs.d/blob/master/site-lisp/persistent-scratch.el

Last was the one I was looking for.

Source of all of them (?):
http://dorophone.blogspot.fr/2011/11/how-to-make-emacs-scratch-buffer.html

Same goal, differents means.

## Regards

Xavier
Sent with my mu4e
