### ISSUE TITLE
If i kill a buffer, then that buffer are dead? (want to persist history)

### ISSUE THREAD

**Issue by snowman** [Fanael/persistent-scratch#23]
Shall we add a customize option that when `persistent-scratch-autosave-mode` is on, call `persistent-scratch-new-backup` each time before auto-save?

And don't forget to set your `persistent-scratch-backup-directory`.

**Comment by Fanael** [comment]
I'm not sure I fully understand your question, could you please rephrase?

**Comment by snowman** [comment]
I mean if I kill a buffer by accident or mistake until I recognized
later, when `persistent-scratch-autosave-mode` is on, it would
automatically save/override the existing
`persistent-scratch-save-file`, then that killed buffer would not able
to restore.

If every time the timer could have a choice to call
`persistent-scratch-new-backup` so that each backup creates a new
backup file, the above scene would not happen.

But this way would create too many backup files, hmmm.

Another solution would be called `persistent-scratch-new-backup` when
killing buffer when necessary, like following:

```elisp
(setq persistent-scratch-backup-directory
      (expand-file-name
       ".persistent-scratchs"
       user-emacs-directory))

(defun persistent-scratch-kill-buffer-query-function ()
  "Back up things before killing scratch buffer."
  (when (funcall persistent-scratch-scratch-buffer-p-function)
    (persistent-scratch-save)
    (persistent-scratch-new-backup))
  t)
(add-hook 'kill-buffer-query-functions
          'persistent-scratch-kill-buffer-query-function)
```

so I now closed this issue, thanks for the code :)
