### ISSUE TITLE
symlink and file rewriting

### ISSUE THREAD

**Issue by grolongo** [Fanael/persistent-scratch#24]
Hello, I've been experimenting with this package today and find it very useful. Thank you.

I'm using Emacs on several machines and tried to use a common `.persistent-scratch` file, just like I do with my `init.el` and a few others.

What I did is put `.persistent-scratch` in a dropbox-like folder and symlink it to the correct path on each machine.

The problem I'm encountering is that each time I close Emacs the `.persistent-scratch` file gets written over and the symlink disappear.

Is there a way to inhibit this behavior so it just saves  instead of completely rewriting?

**Comment by Fanael** [comment]
`persistent-scratch` is using the open-write-rename idiom to ensure atomicity: the save file either contains the old data or the new data, never partially-overwritten invalid data, even in the case of catastrophic system failure. There are no plans to change this behavior.

Of course, this being Emacs, you can always change the behavior through `advice-add` in your own config file.

**Comment by grolongo** [comment]
Fair enough, thank you.
