### ISSUE TITLE
Bad initialisation of org-mode persistant scratch with use-package

### ISSUE THREAD

**Issue by Grumph** [Fanael/persistent-scratch#25]
### Description of the issue

I use my scratch buffer as a TODO list with `org-mode` and `persistent-scratch`.
Everything gets loaded with `use-package` in my init file.

In `org-mode` I need to configure the `org-module` variable, and it must be set before org loads.

If `persistent-scratch` gets loaded before `org-mode`, the latter is not initialized properly (i.e. code in `:init` section of `(use-package org ...` is not loaded, same for depending packages like `org-bullets`). I must set and initialize org before `persistent-scratch` for everything to be fine.

I guess this is not only for org scratch and the behaviour is probably the same with any mode the scratch buffer uses.

### Concrete examples

With this, `org-mode` in scratch is not properly initialized:
```
(use-package persistent-scratch
  :config (persistent-scratch-setup-default))

(use-package org
  :init  (setq org-modules '(org-id ol-info org-protocol)))
```

This works fine:
```
(use-package org
  :init  (setq org-modules '(org-id ol-info org-protocol)))

(use-package persistent-scratch
  :config  (persistent-scratch-setup-default))
```

### Possible actions/solutions

I'm not sure there is something to do here with this issue, but I thought it was worth mentioning it.
Maybe when using `persistent-scratch-setup-default` the restore must be called in `after-init-hook` (it might be something stupid because I don't really know emacs internals, at least I hope you understand what I mean).
Maybe it could be useful to add a sentence in the README to warn users to init `persistent-scratch` after the mode of the scratch buffer.

**Comment by Fanael** [comment]
> If `persistent-scratch` gets loaded before `org-mode`, the latter is not initialized properly (i.e. code in `:init` section of `(use-package org ...` is not loaded, same for depending packages like `org-bullets`). I must set and initialize org before `persistent-scratch` for everything to be fine.

That's to be expected: as far as I understand, `use-package` will immediately load and configure a package, executing the associated forms, before proceeding to the next one, unless you tell it to defer the configuration. If your `use-package org` block is after the `use-package persistent-scratch` one, it's given no chance to run before persistent-scratch does its thing, so you get org-mode with default settings.

> Maybe when using `persistent-scratch-setup-default` the restore must be called in `after-init-hook` (it might be something stupid because I don't really know emacs internals, at least I hope you understand what I mean).

It's probably the best idea if you want to ensure that arbitrarily complex config is executed before `persistent-scratch-setup-default` can do its thing. I don't know `use-package` details, but surely it exposes some way to do that?
