### ISSUE TITLE
How about use `run-with-idle-timer` and with less `persistent-scratch-autosave-interval`?

### ISSUE THREAD

**Issue by snowman** [Fanael/persistent-scratch#26]
https://github.com/Fanael/persistent-scratch/blob/57221e5fdff22985c0ea2f3e7c282ce823ea5932/persistent-scratch.el#L109-L115

https://github.com/Fanael/persistent-scratch/blob/57221e5fdff22985c0ea2f3e7c282ce823ea5932/persistent-scratch.el#L416-L421

Original `persistent-scratch-autosave-interval` is `300` seconds,
but when Emacs abnormally exit, the buffer may not save.

If set to `5` seconds, when you are away from the keyboard, it'll keep running
`persistent-scratch-save` function multiple times regardless of whether idle or not,
but with `run-with-idle-timer`, it runs only *once* when idle.

**Comment by Fanael** [comment]
Can be done now by setting `persistent-scratch-autosave-interval` to, for example, `'(idle . 5)` to save after 5 seconds of idling.
