### ISSUE TITLE
.persistent-scratch looses mode and group

### ISSUE THREAD

**Issue by ghost** [Fanael/persistent-scratch#28]
I mark files that I would like to backup on a regular basis by placing them into group keep. But, every time persistent-scratch saves the file, it the group assigned to it is lost.

I modified persistent-scratch.el causing the file mode and group of a previously existing file (if it exists) to be transferred to the new file. I tested it and it seems to work reliably, so I am happy.

If anyone is interested in the mod, I have created a fork at https://github.com/paulihano/persistent-scratch with the changes. I would rather the author here pull my branch than have yet another fork.

**Comment by ghost** [comment]
This fork solves this problem. I hope it gets pulled.

**Comment by Fanael** [comment]
`persistent-scratch` is using the open-write-rename idiom to ensure atomicity: the save file either contains the old data or the new data, never partially-overwritten invalid data, even in the case of catastrophic system failure.

I'm afraid the approach of shelling out to `chown` is not portable enough, Emacs supports platforms that are not POSIX.

In version 0.3.7 I've introduced a hook `persistent-scratch-before-save-commit-functions`, which allows doing what you want to do (and more!) from your personal config, without having to modify the package.
