### ISSUE TITLE
Question: are there other scratch buffers than *scratch* that this package persists?

### ISSUE THREAD

**Issue by al3xandru** [Fanael/persistent-scratch#29]
(I wish there was a way to ask a question without opening an issue.)

While I am aware of the default `*scratch*` buffer, as a newbie Emacs user, I was wondering if there are any other scratch buffers (say like those that start with `*` for which, if I'm not mistaking, Emacs is not prompting to save them)?

**Comment by Fanael** [comment]
By default, only the `*scratch*` buffer is saved, but this is configurable, see the variable `persistent-scratch-scratch-buffer-p-function`.
