### ISSUE TITLE
Help using persistent-scratch-buffer-p-function

### ISSUE THREAD

**Issue by al3xandru** [Fanael/persistent-scratch#30]
Here's the code I've put in place: 

```lisp
(use-package persistent-scratch
  :ensure t
  :init (with-demoted-errors (persistent-scratch-restore))
  :config
  (persistent-scratch-setup-default)
  (persistent-scratch-autosave-mode 1)
  (defun alpo/scratch-buffer-p ()
    "Return non-nil if the BUFFER (defaults to current buffer) is a scratch buffer."
    (message "called")
    (or (persistent-scratch-default-scratch-buffer-p)
        (string-match-p "^\\*.*\\*$" (buffer-name))))
  (setq persistent-scratch-buffer-p-function #'alpo/scratch-buffer-p))
```

Unfortunately none of the buffers named `*name*` is persisted (or I might have the wrong expectation to see them loaded when restarting Emacs.

**Comment by Fanael** [comment]
The variable you're setting, `persistent-scratch-buffer-p-function`, is not a thing. Are you looking for ` persistent-scratch-scratch-buffer-p-function`?

By the way, it's unlikely that that regular expression is what you want to use, it matches many buffer a lot of buffers that aren't intended to be restored, like `*Messages*`.

**Comment by al3xandru** [comment]
Yes, that's what I was intended to look; and have no clue how I ended up using the other variable :-). Thank you.
