### ISSUE TITLE
Profiling?

### ISSUE THREAD

**Issue by indigoviolet** [Fanael/persistent-scratch#34]
I'm a bit hesitant to post this because I'm only an elisp novice, but I profiled my doom-emacs startup with `benchmark-init` and noticed that `persistent-scratch` stood out as one of the slowest single packages to `require`. 

It's possible that I'm doing something incorrect, so I wanted to ask if you had also tested this and whether it was expected for some reason.

**Comment by Fanael** [comment]
`require`ing persistent-scratch barely does anything at all, it just loads a bunch of variables and functions, so it's hard to believe it's one of the slowest packages to `require`, unless everything else is similarly simple.

There are, however, two plausible explanations:

* the profiling code is not exactly accurate and attributes the cost of something else to persistent-scratch,
* it's not just the cost of `require` it's measuring, but also the cost of restoring the saved buffers, which *could* be slow depending on the amount of data to restore and I/O speed; it still *shouldn't* be slow unless we're dealing with massive amounts of data, however.

**Comment by indigoviolet** [comment]
Thanks for the explanation. I didn't see anything unusual either, hence the question. I'm reasonably certain that your first explanation isn't all of it; plenty of other packages are being measured at a "reasonable"/much lower time than this one, and the ones more expensive than `persistent-scratch` seem plausible, like `lsp`. I guess it could be the latter, but I only have a tiny scratch file. I'll dig some more and report back if I find anything useful.
