### ISSUE TITLE
persistent-scratch-save changes the modification flag of the current buffer

### ISSUE THREAD

**Issue by xampre** [Fanael/persistent-scratch#35]
### Reproduction Steps
1. Open Emacs and create a new file.
2. Edit the buffer to make some changes.
3. Execute persistent-scratch-save.
4. Verify that the buffer modification flag has changed.

### Cause
When executing persistent-scratch-save, (set-buffer-modified-p nil) is being called on the current buffer.

**Comment by Fanael** [comment]
Good catch, thanks.
