### ISSUE TITLE
turn off echo

### ISSUE THREAD

**Issue by fommil** [Fanael/persistent-scratch#4]
It would be good if the "Wrote ..../.persistent-scratch.new" messages were silenced. They often show up in my minibuffer when I'm more interested in other imformation that is or will appear there. I basically don't want to know when the scratch is persisted.

BTW, it seems that the scratch is being saved even if there are no changes required. Is there any way to know what the timestamp of the last edit in a buffer is? If so, you could only save when things change.

**Comment by Fanael** [comment]
> Is there any way to know what the timestamp of the last edit in a buffer is? If so, you could only save when things change.

There is: manually tracking the edit time inside an `after-change-functions` hook.
Please open a separate issue.
