### ISSUE TITLE
persistent *Bookmarks* ?

### ISSUE THREAD

**Issue by fommil** [Fanael/persistent-scratch#7]
is it possible to extend the support to vanilla bookmarks?

**Comment by Fanael** [comment]
Aren't [bookmarks](https://www.gnu.org/software/emacs/manual/html_node/emacs/Bookmarks.html) persistent by default?

> Unlike registers, they have long names, and they persist automatically from one Emacs session to the next.

**Comment by fommil** [comment]
I just started using them and have been too scared to restart! :smile: I'll reopen if I lose them
